name: tsb_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.26.0
  - pandas>=2.2.0
  - scikit-learn>=1.3.2
  - scipy>=1.11.4
  - matplotlib>=3.8.0
  - seaborn>=0.12.2
  - networkx>=3.2
  - pytorch==2.6.0
  - torchvision==0.21.0
  - torchaudio==2.6.0
  - pip
  - pip:
    - transformers>=4.41.0
    - tqdm>=4.66.1
    - torchinfo>=1.8.0
    - h5py>=3.10.0
    - einops>=0.7.0
    - arch>=5.3.1
    - hurst>=0.0.5
    - tslearn>=0.6.3
    - cython>=3.0.10
    - stumpy>=1.12.0
    - scikit-posthocs>=0.7.0 